---
title: "Current opportunities"
description: |
  Any TA, RA or work study opportunities with me (and sometime selected colleagues) will be listed here. *Last updated: 2021-08-31*.
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Research Assistants

None currently, though we may be looking for a few to work on the future of the Independent Summer Statistics Community and for a grant about ethical professional practice for statisticians.

# Work study

See the full posting on [CLNx.utoronto.ca](https://clnx.utoronto.ca/). The direct supervisor is Megan Whitehead-Douglas, but I will also be working closely on this project.

### Who We Are

The Faculty of Arts and Science, Department of Statistical Sciences is a centre for excellence in statistics research and education, both across Canada and internationally. We are a friendly and dedicated team of faculty and staff members who want to support students in their academic and career goals.\
 \
This role will be based within a larger team of faculty, staff and research assistants working on integrating meaningful ethics education across the undergraduate statistics experience. This project will involve curriculum development across multiple courses as well as a focus on developing resources for career education linked to ethical practice.\
 \
You will be welcomed and supported within the larger research team, as well as having to opportunity to get to know other Department of Statistical Sciences students in related roles.\
 

### What We Value 

The University of Toronto is strongly committed to diversity within its community and especially welcomes applications from racialized persons / persons of colour, women, Indigenous / Aboriginal People of North America, persons with disabilities, LGBTQ persons, and others who may contribute to the further diversification of ideas.\
 

### What You'll Be Doing

#### Overview of role

The focus of this position will be on gathering, synthesizing, and communicating information about ethical practice in statistics and data science careers to support career education for Department of Statistical Sciences students. This role is funded for up to 100 hours across Fall/Winter 2021-22.

####  Responsibilities 

In this role, your first main task will be to perform an environmental scan of the Canadian employment market to collate job description examples, company statements and reports and other relevant documents and media about ethical practice with regard to statistics and data work. You will identify and recommend other relevant markets/global information to collect and explore, in partnership with your supervisor.\
 \
You will work with your supervisor to identify the most useful information for undergraduate students and develop this into student-facing information through appropriate mediums, such as infographics, blog posts, videos, etc.\
 \
You will also have additional tasks in support of the research team. You will have the opportunity to discuss which of these areas you are most interested in/have the best skills alignment for.\
 \
Additional tasks could include:

-   developing a Distill/R Markdown website the project

-   helping with the write-up/formatting of website content

-   taking meeting notes

-   conducting interviews

-   developing activities

-   liaising with campus groups with relevant interests and sharing profiles

-   creating reading lists for general interest texts related to ethical practice in statistics and data science

-   proposing additional activities related to

###  **Desired Skills and Experience**

#### Education

Being enrolled in, or having previously undertaken, a statistics program of study or other data-oriented program/courses is an advantage.

#### Experience

No specific previous experience is required, but it will be advantageous to highlight experiences through which you can demonstrate that you have the below competencies.\

#### Competencies

-   **Excellent written and verbal communication**:  professional, polite, friendly, you must be able to understand and clearly explain concepts and ideas 

-   **Time management and prioritization**: able to keep track of multiple projects and priorities simultaneously (including your own school commitments!) 

-   **Excellent research/inquiry skills**: ability to synthesize information from a large range of sources; know where to look for information and how to sort what is important; able to look beyond the surface and mine for details 

-   **Teamwork**

Additionally, competencies in any of the following areas are advantages: public speaking, R and/or Python programming, website design, Git and GitHub, event coordination, taking meeting notes, Indigenous cultural knowledge (we will look at Indigenous Data Sovereignty), EDI initiatives, reproducibility, human/animal research ethics, algorithmic bias, web scraping, disclosure risk, data privacy, data visualization (and how not to lie with graphs), designing for accessibility/universal design for learning.

####  Availability requirements

In this role you will set plans and goals with your supervisor and be able to flexibly arrange deadlines and work, e.g., you can set whether you'd like to work during reading weeks.\
 \
Meetings will be scheduled during weekdays between 9:00 a.m. and 5:00 p.m. ET and can be held online or in-person depending on public health guidelines and the comfort of those attending. Other than attending meetings, there are not fixed times you will be required to be available-you will lead setting your goals and schedule for each week with support from your supervisor.

# Teaching Assistants

See the [Department Website for full information](https://www.statistics.utoronto.ca/employment-opportunities/cupe-positions-unit-1#teaching-assistants-accordion-1).

Each summer these advertisements go up. I don't oversee the hiring, but I do love to know if you've applied and I am happy to answer questions about the course format and what the experience would be like. I can't answer questions about eligibility/visas etc.

There are also occasionally emergency postings outside of the usual summer recruitment drive.

-   STA130 accepts undergraduate students as TAs, but grad students are given priority. R users in other disciplines with a good statistical grounding are also encouraged to apply.
-   STA303 accepts Masters students and above. R users in other disciplines with a good statistical grounding are also encouraged to apply.
-   STA490 accepts PhD students in Statistical Sciences.
