---
title: "Reference letters"
description: | 
  A guide to requesting reference letters from me.  *Last updated: 2023-12-24*.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Grad school references

If you're aiming for grad school, you'll most likely need a few Profs to agree to write letters/fill out forms in support of your application. Be prepared for this and start thinking about it early. You should also always ask first, before you put someone's name down. This is also true for job reference etiquette generally.

My policy is not to agree to write a reference for students if they have not **completed** a course with me.

To be able to write a reference that would actually strengthen your application, my usual minimum criteria is at least two out of the following activities with me:

-   active on Piazza (or Ed Discussion)/office hours AND good mark in a standard class-based course (like STA303) [PLEAE NOTE, all of this counts as ONE activity and one course is not enough by itself unless I have told you otherwise],
-   student representative role,
-   RA work,
-   TA work
-   a reading course.

Some examples of students I have said yes to (Univeristy of Toronto):

-   several students who had high marks in STA303 and were active and doing well in STA490 with me,
-   students who had done STA303 and gone on to do great work as TAs or peer mentors for STA130 when I was teaching, and
-   a student who had done STA303 and was working on a reading course with me.

Further things to keep in mind:

-   I need at least 3--5 week's notice before your reference is due.

-   I will write in support of 3 programs per student.

-   I will only agree if I can write you a *strong* letter. Anything less is a waste of your and my time. Example of things I am frequently asked to rate about students that a good grade alone won't tell me:

    -   Clarity of Goals for Graduate Study

    -   Oral Expression in English

    -   Ability to Work Independently

    -   Ability to Work with Others

    -   Research Potential

    -   Motivation

    -   "Humility" and "sense of humour" are other examples that I personally hate, but your chosen program(s) might ask.

-   If offered (i.e., if there is a tick box), **please waive your right to access the report**. (You can ask me directly if I am comfortable sharing it with you.) This is usually just for American schools, you can read more [here](https://blog.prepscholar.com/should-you-waive-right-to-review-letters-of-recommendation).

-   DON'T offer to write a draft for me (I don't accept this, and schools may ask you to declare something like "I confirm that I will not write any portion of this evaluation, nor will I have any involvement in its drafting or submission." anyways), DO provide lots of specific details, examples and relevant files when completing the request form or subsequent details form (there is a second form if I approve you first request). Tell me enough that I could approve/write this even if I got partial amnesia.

### What should you do if you think you fit my criteria?

**I am not currently taking new requests until February 2024.**

Requests sent to the UofT form in the second half of 2023 were not available to me as I am no longer with the University of Toronto. My apologies for not updating the instructions here sooner to reflect that.

[~~If you believe you meet my basic criteria, you can request a reference from me [here](https://forms.office.com/r/ycetDQdnFP).~~]{style="background-color: #FFD700"} ~~I will then accept or decline based on the the information provided.~~

## Industry *then* grad school? How to ask about references for a few years from now

Several students have very sensibly asked what they should do if they plan to work for a year or two before grad school. A great question and my attempt to provide some clarity below.

So firstly, the 'two activity criterion' (from above) still applies, but you don't need to fill out the form *now*.

#### What you should do *now*:

-   IFF (if and only if) you meet my criteria, let me know that this is what you're considering. Do it via **email** so a few years from now when you ask and I search your name, I'll have a record of the conversation.\

-   Create a folder/document with notes about the things I might know about you.

    -   Save copies of any assignments you're particularly proud of (like a STA130/STA303/STA490 final project (UofT)) and make note of whether you did it as a group, what the grade you got was etc. Don't assume future you will remember this. Future me definitely won't!

#### What you should do when you're *planning to apply*:

-   Make sure you plan ahead and get a sense of the deadlines from programs you are interested in. Aim to get back in touch with me (see next point) 5--6 weeks before your first due date.
-   Check back on this page to see what my request instructions are (i.e., there is currently a request form linked above) and follow any instructions provided. This is where your notes will come in handy! You can even add a link to the folder (make sure it is not password protected) as part of the request.

## General tips and advice

See my general advice [here](https://www.lizabolton.com/advice.html#reference-letters).

## References for other things?

This will be on a bit more of a case-by-case basis. I really do want to support as many of you as I can! Email me directly to discuss jobs/scholarships/internships etc. **Please keep in mind, if all I can say about you is that "Student X took my course and got grade Y", I'm not going to be very useful to you.**

Please also note that you should also always ask first, before you put someone's name down.
