---
title: "Talks and media"
description: |
  Sometimes I say stuff. Actually, quite often...but sometimes it's worth sharing!
output: distill::distill_article
---

## _Panel on teaching data-focussed topics_, Toronto Data Workshop


_2020-12-17_

Big thank you to [Rohan Alexander](https://rohanalexander.com/) for organising this panel on teaching data-focussed topics. This was one of my favourite talks I've ever done because I got to get creative with it. Unfortunately my use of music kept getting Rohan copyright stuck on YouTube. Sorry, Rohan!

<iframe width="560" height="450" src="https://www.youtube.com/embed/c3R6pZisvm0?start=894"  allowfullscreen></iframe>

My bit starts at 14:51 but I'd highly recommend the other speakers' sections!

#### Fellow panellists:

* [Nathalie Moon, Univeristy of Toronto](https://www.statistics.utoronto.ca/people/directories/all-faculty/nathalie-moon)
* [Maria Tackett, Duke University](https://www.mariatackett.net/)
* [Teon Brooks, Mozilla Firefox](https://teonbrooks.com/)

## _Everything you need to fall in love with Statistics_, an interview with [storyo.co](https://www.storyo.co/)

_2019-07-11_    

> I met Liza (pronounced Lie-zuh, like Liza Minnelli) at the R-Ladies meetup in Auckland, New Zealand where she was giving a talk on colour palettes. If you ever meet Liza, you will see that it is absolutely impossible to not get a massive positive energy recharge after talking to her. Liza is currently doing her PhD in Statistics, running a consultancy called The Data Embassy, speaking at events, teaching, mentoring. It would be my absolute pleasure to learn more about Liza and share her wonderful story.

[Read the full interview here](https://www.storyo.co/stories/liza-bolton)

## _Don’t cha wish your ggplot had colours like me?_, R Ladies Auckland

_2019-06-12_

A lightning talk about using colour when plotting data with `ggplot`.

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(url = "https://www.dataembassy.co.nz/Liza-colours-in-R#1", ratio = "16:9")
```

